spring:
    application:
       name: Config-Dev
eureka:
    instance:
       prefer-ip-address: true
       register-with-eureka: true
       server-url:
          defaultZone: http://localhost:8761/eureka
